### ISSUE TITLE
getcomposer link in readme leads to phishing site

### ISSUE THREAD

**Issue by 324705** [RubixML/MNIST#2]
the correct link to get composer is

https://getcomposer.org/

and not

getcomposer com

![grafik](https://user-images.githubusercontent.com/26047960/64168636-41e6ec80-ce4c-11e9-9318-60bd85e2750e.png)

**Comment by andrewdalpino** [comment]
Thank you for noticing and for taking the time to submit a report

The link has now been fixed

Don't hesitate to let us know if you find anything else like this in the future

Welcome to our community @324705
